// Copyright 2022 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics -i arrow-top-left-bold-box-outline.png -f mono2`

#pragma once

#include <qp.h>

extern const uint32_t gfx_arrow_top_left_bold_box_outline_length;
extern const uint8_t  gfx_arrow_top_left_bold_box_outline[54];
