// Copyright 2022 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics -i image-size-select-small.png -f mono2`

#pragma once

#include <qp.h>

extern const uint32_t gfx_image_size_select_small_length;
extern const uint8_t  gfx_image_size_select_small[180];
