// Copyright 2022 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics -i relation-zero-or-one-to-only-one.png -f mono2`

#pragma once

#include <qp.h>

extern const uint32_t gfx_relation_zero_or_one_to_only_one_length;
extern const uint8_t  gfx_relation_zero_or_one_to_only_one[54];
