// Copyright 2022 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics -i screw-round-top.png -f mono2`

#pragma once

#include <qp.h>

extern const uint32_t gfx_screw_round_top_length;
extern const uint8_t  gfx_screw_round_top[248];
